on:
  push:
    branches:
      - main
      - rama-develop-pre-presentacion
  pull_request:
    branches:
      - main
      - rama-develop-pre-presentacion

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Descargar cÃ³digo del repositorio
        uses: actions/checkout@v3

      - name: ğŸ§° Instalar .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x" # CambiÃ¡ por la versiÃ³n que uses (ej. '8.0.x' o '6.0.x')

      - name: ğŸ§¹ Limpiar y restaurar dependencias
        run: |
          dotnet nuget locals all --clear
          dotnet restore --force-evaluate


      - name: ğŸ› ï¸ Compilar la soluciÃ³n
        run: dotnet build --no-restore --configuration Release #run: dotnet build ./src/MiProyecto/MiProyecto.csproj --no-restore Esto si el .sln no estÃ¡ en la raÃ­z del proyecto

      - name: ğŸ§ª Ejecutar tests
        run: |
          dotnet test alquimia.Tests/alquimia.Tests.csproj --configuration Debug --verbosity normal

      - name: âœ… Fin del proceso
        run: echo "âœ”ï¸ Workflow completado correctamente."
